apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: rakhicc/ping-pong:v10
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3007"
            - name: DATABASE_URL
              value: "postgres://pinguser:securepassword@postgres-db-0.postgres-db-service:5432/pingpong_db"    