apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- backup-cronjob.yaml

patches:
- path: broadcaster-patch.yaml
- path: backend-patch.yaml


namePrefix: prod-