apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patches:
- path: broadcaster-patch.yaml

images:
- name: PROJECT/IMAGE
  newName: rakhicc/todo-node

namePrefix: staging-