apiVersion: apps/v1
kind: Deployment
metadata:
  name: todofrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todofrontend
  template:
    metadata:
      labels:
        app: todofrontend
    spec:
      containers:
        - name: todofrontend
          image: todo-frontend-placeholder-image
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: todofrontend-config
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"     
          
