apiVersion: apps/v1
kind: Deployment
metadata:
  name: todofrontend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todofrontend
  template:
    metadata:
      labels:
        app: todofrontend
    spec:
      volumes:
        - name: shared-todocache
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todofrontend
          image: rakhicc/todofrontend:v10
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: todofrontend-config

          volumeMounts:
          - name: shared-todocache
            mountPath: /data
          
