apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: project
data:
  PORT: "3000"

  # ✅ image source
  IMAGE_URL: "https://picsum.photos/1200"

  # ✅ cache duration (in ms)
  IMAGE_CACHE_TIME: "600000"

  # ✅ storage path
  DATA_DIR: "/data"