apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      volumes:
        - name: shared-todocache
          persistentVolumeClaim:
            claimName: todo-claim

      containers:
        - name: todobackend
          image: rakhicc/todobackend:v13
          imagePullPolicy: Always

          volumeMounts:
            - name: shared-todocache
              mountPath: /data

          envFrom:
            - configMapRef:
                name: todo-backend-config

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password