apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      volumes:
        - name: shared-todocache
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todobackend
          image: rakhicc/todobackend:v11
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-todocache
            mountPath: /data
          