apiVersion: v1
data:
  config.yaml: |
    additional_display_details:
    - annotation: kiali.io/api-spec
      icon_annotation: kiali.io/api-type
      title: API Documentation
    auth:
      openid: {}
      openshift:
        client_id_prefix: kiali
      strategy: anonymous
    chat_ai:
      default_provider: ""
      enabled: false
      providers: []
      store_config:
        enabled: true
        max_cache_memory_mb: 1024
        reduce_threshold: 15
        reduce_with_ai: false
    clustering:
      autodetect_secrets:
        enabled: true
        label: kiali.io/multiCluster=true
      clusters: []
    deployment:
      additional_pod_containers_yaml: []
      additional_pod_init_containers_yaml: []
      additional_service_yaml: {}
      affinity:
        node: {}
        pod: {}
        pod_anti: {}
      cluster_wide_access: true
      configmap_annotations: {}
      custom_envs: []
      custom_secrets: []
      discovery_selectors: {}
      dns:
        config: {}
        policy: ""
      extra_labels: {}
      host_aliases: []
      hpa:
        api_version: autoscaling/v2
        spec: {}
      image_digest: ""
      image_name: quay.io/kiali/kiali
      image_pull_policy: IfNotPresent
      image_pull_secrets: []
      image_version: v2.26
      ingress:
        additional_labels: {}
        class_name: nginx
        override_yaml:
          metadata: {}
      ingress_enabled: false
      instance_name: kiali
      logger:
        log_format: text
        log_level: info
        sampler_rate: "1"
        time_field_format: 2006-01-02T15:04:05Z07:00
      namespace: istio-system
      network_policy:
        enabled: false
      node_selector: {}
      pod_annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      pod_disruption_budget:
        api_version: policy/v1
        spec: {}
      pod_labels:
        sidecar.istio.io/inject: "false"
      priority_class_name: ""
      probes:
        liveness:
          initial_delay_seconds: 5
          period_seconds: 30
        readiness:
          initial_delay_seconds: 5
          period_seconds: 30
        startup:
          failure_threshold: 6
          initial_delay_seconds: 30
          period_seconds: 10
      remote_cluster_resources_only: false
      replicas: 1
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 64Mi
      secret_name: kiali
      security_context: {}
      service_annotations: {}
      service_type: ""
      strategy: {}
      tls_config:
        cipher_suites: []
        max_version: ""
        min_version: ""
        source: config
      tolerations: []
      topology_spread_constraints: []
      version_label: v2.26.0
      view_only_mode: false
    external_services:
      custom_dashboards:
        enabled: true
      istio:
        root_namespace: istio-system
      prometheus:
        enabled: true
        url: http://prom-prometheus-server.monitoring:80
      tracing:
        enabled: false
    identity:
      cert_file: ""
      private_key_file: ""
    kiali_feature_flags:
      custom_workload_types: []
      disabled_features: []
      validations:
        ignore:
        - KIA1301
    login_token:
      signing_key: CHANGEME00000000
    server:
      observability:
        metrics:
          enabled: true
          health_status:
            enabled: false
            max_consecutive_na: 3
          port: 9090
      port: 20001
      web_root: /kiali
    skipResources: []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"additional_display_details:\n- annotation: kiali.io/api-spec\n  icon_annotation: kiali.io/api-type\n  title: API Documentation\nauth:\n  openid: {}\n  openshift:\n    client_id_prefix: kiali\n  strategy: anonymous\nchat_ai:\n  default_provider: \"\"\n  enabled: false\n  providers: []\n  store_config:\n    enabled: true\n    max_cache_memory_mb: 1024\n    reduce_threshold: 15\n    reduce_with_ai: false\nclustering:\n  autodetect_secrets:\n    enabled: true\n    label: kiali.io/multiCluster=true\n  clusters: []\ndeployment:\n  additional_pod_containers_yaml: []\n  additional_pod_init_containers_yaml: []\n  additional_service_yaml: {}\n  affinity:\n    node: {}\n    pod: {}\n    pod_anti: {}\n  cluster_wide_access: true\n  configmap_annotations: {}\n  custom_envs: []\n  custom_secrets: []\n  discovery_selectors: {}\n  dns:\n    config: {}\n    policy: \"\"\n  extra_labels: {}\n  host_aliases: []\n  hpa:\n    api_version: autoscaling/v2\n    spec: {}\n  image_digest: \"\"\n  image_name: quay.io/kiali/kiali\n  image_pull_policy: IfNotPresent\n  image_pull_secrets: []\n  image_version: v2.26\n  ingress:\n    additional_labels: {}\n    class_name: nginx\n    override_yaml:\n      metadata: {}\n  ingress_enabled: false\n  instance_name: kiali\n  logger:\n    log_format: text\n    log_level: info\n    sampler_rate: \"1\"\n    time_field_format: 2006-01-02T15:04:05Z07:00\n  namespace: istio-system\n  network_policy:\n    enabled: false\n  node_selector: {}\n  pod_annotations:\n    proxy.istio.io/config: '{ \"holdApplicationUntilProxyStarts\": true }'\n  pod_disruption_budget:\n    api_version: policy/v1\n    spec: {}\n  pod_labels:\n    sidecar.istio.io/inject: \"false\"\n  priority_class_name: \"\"\n  probes:\n    liveness:\n      initial_delay_seconds: 5\n      period_seconds: 30\n    readiness:\n      initial_delay_seconds: 5\n      period_seconds: 30\n    startup:\n      failure_threshold: 6\n      initial_delay_seconds: 30\n      period_seconds: 10\n  remote_cluster_resources_only: false\n  replicas: 1\n  resources:\n    limits:\n      memory: 1Gi\n    requests:\n      cpu: 10m\n      memory: 64Mi\n  secret_name: kiali\n  security_context: {}\n  service_annotations: {}\n  service_type: \"\"\n  strategy: {}\n  tls_config:\n    cipher_suites: []\n    max_version: \"\"\n    min_version: \"\"\n    source: config\n  tolerations: []\n  topology_spread_constraints: []\n  version_label: v2.26.0\n  view_only_mode: false\nexternal_services:\n  custom_dashboards:\n    enabled: true\n  istio:\n    root_namespace: istio-system\n  prometheus:\n    enabled: true\n  tracing:\n    enabled: false\nidentity:\n  cert_file: \"\"\n  private_key_file: \"\"\nkiali_feature_flags:\n  custom_workload_types: []\n  disabled_features: []\n  validations:\n    ignore:\n    - KIA1301\nlogin_token:\n  signing_key: CHANGEME00000000\nserver:\n  observability:\n    metrics:\n      enabled: true\n      health_status:\n        enabled: false\n        max_consecutive_na: 3\n      port: 9090\n  port: 20001\n  web_root: /kiali\nskipResources: []\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"kiali","app.kubernetes.io/instance":"kiali","app.kubernetes.io/name":"kiali","app.kubernetes.io/part-of":"kiali","app.kubernetes.io/version":"v2.26.0","helm.sh/chart":"kiali-server-2.26.0","version":"v2.26.0"},"name":"kiali","namespace":"istio-system"}}
  creationTimestamp: "2026-07-08T11:39:08Z"
  labels:
    app: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v2.26.0
    helm.sh/chart: kiali-server-2.26.0
    version: v2.26.0
  name: kiali
  namespace: istio-system
  resourceVersion: "1410"
  uid: 038c2109-e4b8-49db-b259-6e11d02a666f
