apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: rakhicc/log-output-node:v7
          env:
            - name: PORT
              value: "3008"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE

          volumeMounts:          # ✅ must be inside container
            - name: config-volume
              mountPath: /etc/config
              readOnly: true

      volumes:                  # ✅ same level as containers
        - name: config-volume
          configMap:
            name: log-output-config