apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-count
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: log-output
          image: rakhicc/log-output-node:v3
          volumeMounts:
          - name: shared-count
            mountPath: /data
          env:
            - name: PORT
              value: "3000"