apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-output
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rakhicc/KubernetesSubmissions.git
    targetRevision: main
    path: log_output/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: project

  syncPolicy:
    automated:
      prune: true
      selfHeal: true