apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: course-ingress
spec:
  rules:
    - http:
        paths:
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: ping-pong-svc # 👈 Routes public-ip/pingpong to your pingpong application
                port:
                  number: 80
          - path: /pings
            pathType: Prefix
            backend:
              service:
                name: ping-pong-svc # 👈 Routes public-ip/pingpong to your pingpong application
                port:
                  number: 80              
          - path: /logoutput # 👈 Routes all other traffic (including health checks) to your log output application
            pathType: Prefix
            backend:
              service:
                name: log-output-svc # 👈 Ensure this matches your log output Service resource name
                port:
                  number: 80
          - path: / # 👈 Routes all other traffic (including health checks) to your log output application
            pathType: Prefix
            backend:
              service:
                name: log-output-svc # 👈 Ensure this matches your log output Service resource name
                port:
                  number: 80       
