apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:

      containers:
        - name: todobackend
          image: todo-backend-placeholder-image
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: todo-backend-config

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password