apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
  namespace: project

spec:
  replicas: 6

  selector:
    matchLabels:
      app: broadcaster

  template:
    metadata:
      labels:
        app: broadcaster

    spec:
      containers:
        - name: broadcaster

          image: broadcaster-placeholder-image

          env:
            - name: NATS_URL
              value: nats://my-nats.nats.svc.cluster.local:4222

            - name: WEBHOOK_URL
              value: https://webhook.site/your-id