apiVersion: apps/v1
kind: Deployment
metadata:
  name: todofrontend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todofrontend
  template:
    metadata:
      labels:
        app: todofrontend
    spec:
      containers:
        - name: todofrontend
          image: todo-frontend-placeholder-image
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: todofrontend-config
          
