name: Delete environment

on:
  delete:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  delete-environment:
    runs-on: ubuntu-latest
    environment: GKE_PROJECT

    # Only run when a branch is deleted
    if: github.event.ref_type == 'branch'

    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Delete namespace
        run: |
          BRANCH=${{ github.event.ref }}

          echo "Deleted branch: $BRANCH"

          if [ "$BRANCH" = "main" ]; then
            echo "Skipping deletion of project namespace"
            exit 0
          fi

          kubectl delete namespace $BRANCH --ignore-not-found=true